name: Commit Changes to javax branch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  run_script_and_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: master
    - name: convert to javax
      run: |
        ./jakarta-to-javax.sh

    - name: Configure Git for commit
      run: |
        git config user.name "GitHub Action"
        git config user.email "github-action@users.noreply.github.com"

    - name: Check for changes and commit
      id: commit_changes
      run: |
        git add .
        git diff-index --quiet HEAD || git commit -m "Automated commit by GitHub Action - Triggered by commit_sha: ${{ github.sha }}"
    - name: Push changes to javax.main branch (force overwrite on conflict)
      run: |
        # Fetch the remote branch to ensure it exists locally if created recently
        git fetch origin javax.main || true

        # This command pushes the current HEAD (which contains the changes from your script
        # on top of the 'main' branch) to 'javax.main'.
        # The '--force-with-lease' option is safer than '--force' as it prevents overwriting
        # changes if someone else pushed to 'javax.main' after you fetched.
        # If the branch 'javax.main' does not exist, it will be created.
        git push origin HEAD:javax.main --force-with-lease
